# TODO Start: [Student] Change registry to your Secoder instance
image: registry.spring25b.secoder.net/tool/deployer
# TODO End: [Student] Change registry to your Secoder instance

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  # TODO End: [Student] Set as only main
  only:
    - dev

unit-test:
  # TODO Start: [Student] Set job image
  image: python:3.11
  # TODO End: [Student] Set job image
  stage: test
  before_script:
    # TODO Start: [Student] Install dependencies
    - pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    # TODO End: [Student] Install dependencies
  script:
    # TODO Start: [Student] Migrate and run tests
    - python manage.py makemigrations ims
    - python manage.py migrate
    - bash test.sh
    # TODO End: [Student] Migrate and run tests
  after_script:
    - SUFFIX=$RANDOM
    # TODO Start: [Student] Secoder URL
    - curl "http://api.spring25b.secoder.net/static/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - sed -i 's/sonarqube.secoder.net/sonarqube.spring25b.secoder.net/g' /opt/sonar-scanner/conf/sonar-scanner.properties
    - sed -i 's/api.secoder.net/api.spring25b.secoder.net/g' /opt/sonar-scanner/bin/sonar-scanner
    # TODO End: [Student] Secoder URL
    - /opt/sonar-scanner/bin/sonar-scanner
  allow_failure: true

deploy:
  stage: deploy
  script:
    - export API_SERVER=https://deployer.spring25b.secoder.net/api
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  # TODO End: [Student] Set as only main
  only:
    - dev